<?php
/**
 * @file
 * Code for the GSB Feature Files FPP feature.
 */

include_once 'gsb_feature_files_fpp.features.inc';
/**
 * @file
 * Code for the GSB Feature Files FPP feature.
 */

/**
 * Implements hook_entity_info_alter().
 */
function gsb_feature_files_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['files'] = array(
    'label' => t('Files'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/files',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
/**
 * Implements template_preprocess_fieldable_panels_pane()
 */
function gsb_feature_files_fpp_preprocess_fieldable_panels_pane (&$variables) {
  if ($variables['elements']['#bundle'] == 'files') {
    $wrapper = entity_metadata_wrapper($variables['elements']['#entity_type'], $variables['elements']['#element']);
    // Determine the file container style and set corresponding style class for pane.
    $variables['classes_array'][] = $wrapper->field_files_style->value();
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form().
 */
function gsb_feature_files_fpp_form_fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'fieldable_panels_panes_fieldable_panels_pane_content_type_edit_form' && $form['#bundle'] == 'files') {
    $form['#after_build'][] = 'gsb_feature_files_fpp_edit_form_alter';
  }
}

/**
 * Hides the Upload buttons on the edit form for the public and private file field collections.
 */
function gsb_feature_files_fpp_edit_form_alter($form) {
  $language = $form['language']['#value'];
  $file_fields = array(
    'field_file_unlimited_public',
    'field_file_unlimited_private'
  );
  foreach($file_fields as $name) {
    foreach($form[$name][$language] as $key => $item) {
      if (!empty($form[$name][$language][$key]['upload_button'])) {
        $form[$name][$language][$key]['upload_button']['#prefix'] = '<div class="element-hidden">';
        $form[$name][$language][$key]['upload_button']['#suffix'] = '</div>';
      }
    }
  }
  return $form;
}
